global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:4001']
    metrics_path: '/metrics'

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:4002']
    metrics_path: '/metrics'

  - job_name: 'vendor-service'
    static_configs:
      - targets: ['vendor-service:4003']
    metrics_path: '/metrics'

  - job_name: 'booking-service'
    static_configs:
      - targets: ['booking-service:4004']
    metrics_path: '/metrics'

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:4005']
    metrics_path: '/metrics'

  - job_name: 'execution-service'
    static_configs:
      - targets: ['execution-service:4006']
    metrics_path: '/metrics'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:4008']
    metrics_path: '/metrics'

  - job_name: 'review-service'
    static_configs:
      - targets: ['review-service:4009']
    metrics_path: '/metrics'

  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:4010']
    metrics_path: '/metrics'

  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:4011']
    metrics_path: '/metrics'

  - job_name: 'media-service'
    static_configs:
      - targets: ['media-service:4012']
    metrics_path: '/metrics'
